### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by SunnysTTV** [MayhemStudios/FiveMReadyMaps#3]
hey there.. sorry about the last map.. i think this maybe has the same issue? if not it would be so nice..
https://de.gta5-mods.com/maps/house-on-the-rock

**Comment by ElixerDevelopment** [comment]
Hello again. 
Thanks for another suggestion. I'll get to testing this shortly.

**Comment by ElixerDevelopment** [comment]
Unfortunately, This map is broken as-well, I would recommend other ones that are compatible with **menyoo** or **map editor** as these are the easiest to convert however, they are more likely to work on FiveM.

Most maps that are available via a **dlc.rpf** contains a **Non Streamable Object**. I have attached an image of what the map looks like if you have it streamed to FiveM. The walls don't work, however the windows do, and it is the same issue as your **"LogHouse"** suggestion.

![image](https://user-images.githubusercontent.com/55484272/198742034-371dc0be-5133-4986-8052-5cd9f91cfe29.png)
