### ISSUE TITLE
Snowy Christmas Island

### ISSUE THREAD

**Issue by boolee4web** [MayhemStudios/FiveMReadyMaps#4]
My game load this map properly, but I can only see objects like building, trees and pedestrians, the ground is missing. What should I do?

**Comment by ElixerDevelopment** [comment]
Could you please explain what map this is exactly, and can i please get a screenshot, To assist i am going to need more information.

**Comment by boolee4web** [comment]
https://prnt.sc/Srk20XIlu4BT

merryxmas map

**Comment by ElixerDevelopment** [comment]
Hello, So i have found the issue to this problem, The issue seems to be that the map creator, (who originally designed the map for singleplayer) has an object that is not stream able by FiveM, causing that specific object to be invisible, There is no fix to this. That map has since been removed.
